version: "3.9"
services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - finex_db_vol:/data/db
    networks:
      - finex_net

networks:
  finex_net:
    name: finex_net
    driver: bridge

volumes:
  finex_db_vol:
